### DISCUSSION TITLE
Collaborating with Forks

### DISCUSSION THREAD

**Discussion by Shadow53** [Shadow53/hoard#35] [General]
@lmburns, I notice you've been doing work in a fork of this project. I was wondering if you are planning on submitting any of those changes for upstream consideration (with relevant issues, as needed) or if you intend to maintain your own personal fork.

I'm opening this discussion here since I did not see a good way to contact you through the forked repo.

**Comment by lmburns** [comment]
Sorry about the delay in a response to your message. I need to setup GitHub emails differently so I see them every time.

But sure, I would be more than happy to collaborate on this project with you if that is what you wanted to do. I am just in the process of learning Rust and decided that since I use your program, I was going to fork it and add features to it while trying to learn Rust.

I'm not sure the direction that you plan on taking this project, and I see that you're a way better programmer than I am, so if you would like for me to try and work on something and then push the changes upstream for you to review, I'd be more than happy to.

### `XDG` Folder Structure
For my fork, since I currently use `macOS` (am switching to Linux next week), and I use many many programs that all respect the `XDG` folder structure, I switched from simply using `dirs::config_dir()` and other functions for that crate, to using the `XDG` structure if set, and falling back to the manual `$HOME/.config` structure for `macOS`, and the `dirs::...` functions for all other operating systems.

### File Formats
I also added compatibility for 3 file formats, `toml`, `json`, and `yaml`. I personally prefer `yaml` in the context of this program. It seems to be less repetitive, i.e., in a `toml` structure the format goes like so:
```toml
[hoards]
[hoards.file]
  [hoards.file.config]
    [hoards.file.config.encryption]
```
And a `yaml` structure goes in the following:
```yaml
hoards:
  file:
    config:
      encryption
```

Just because, I added a way to convert between formats and still need to check whether your `combinators` works when using a `yaml` and `json` structure. I think that it does for `yaml`. The `toml` structure goes like:
```toml
[envs.itch]
    path_exists = [[
        "/home/shadow53/.itch",
        "/home/shadow53/.local/share/applications/io.itch.itch.desktop"
    ]]
```

`yaml` is:
```yaml
envs:
  itch:
    path_exists:
      - - /home/shadow53/.itch
        - /home/shadow53/.local/share/applications/io.itch.itch.desktop
```

### Added ability to preview configuration file (colorized) and add items through the CLI
This was modified from `bat`. This feature is not needed at all, but I had planned on creating some sort of way in which the user could add items to the configuration through the command line without ever having to open the configuration file. This would be an option to preview the configuration file. I would like this feature so that way whenever I add a new file that I want to backup, I could add it with ease. There could be a way that this creates an `env` for a specific executable and adds a path, or something along these lines. I haven't really attempted to work on the feature yet.

### `shellexpand`
I modified the original `shellexpand` to include expanding nested default values (this is the way that normal shell expansion works). The regular crate will only expand `${ZDOTDIR:-/Users/user/.config/zsh}`, the modified version will expand `${ZDOTDIR:-$HOME/.config/zsh}`.

### Use `ignore` crate for user options when walking directories
When using the `ignore` crate, many options are provided that the user can fill out. This includes things such as following symlinks, copying hidden files, only matching a certain pattern, setting a max depth, whether the pattern is a regular expression or a glob, whether the pattern is case-insensitive, and patterns to exclude. I also added a global option that is in the format of a `gitignore` file, that will globally ignore certain patterns (provided by the `ignore` crate).

Example configuration:
```toml
[global_config]
    ignores = ["exe/"]
[hoards]
[hoards.fish]
    [hoards.config]
        # Whether or not to follow symlinks
        "follow_links" = true
        # Whether or not to skip hidden files
        "hidden" = true
        # Pattern of files to only include
        "pattern" = "*.txt"
        # Whether the pattern is to be interpreted as a regex or a glob
        "regex" = true
        # Max depth to traverse
        "max_depth" = 2
        # Whether the pattern should be case sensitive or not
        "case_sensitive" = false
        # Patterns to exclude (notice they are regex patterns, not like the ignores pattern above)
        "exclude" = ["*patt*"]
    [hoards.fish.confdir]
        "linux|fish" = "/home/shadow53/.config/fish/conf.d"

```

### Encryption
I also started to implement the encryption part of the configuration that you had planned. I used `gpgme` to set this up and took parts of it from another fork that I am working on `prs`. This should be modified more and functions that are unnecessary need to be removed. I have the `asymmetric` encryption down, however, for the `symmetric` encryption, I am able to use `gpg`'s symmetric flags, but it prompts the user for every file it comes across and I cannot figure out a way to capture a password from the configuration file or from the user through the CLI.

I would like to see how you planned on implementing this.

If any of these features sound like something that would like for me to re-fork your project and implement on that fork to push upstream, I definitely can do this. Like I said, I am learning Rust and have been forking projects to do this, so what I do may not be the best.
