### ISSUE TITLE
Multiple files/folders for one target

### ISSUE THREAD

**Issue by Shadow53** [Shadow53/hoard#9]
Needed for #5 and blocked by #8.

The current basic design assumes either a single file or a single directory of which everything will be stored.

This needs a way to specify multiple files/folders for a target (easy) and a way to define where those files/folders can be found in different environments (harder).

As a simple example: Vim/Neovim on Windows/Linux.

- Vim:
  - Linux: `$HOME/.vimrc` and `~/.vim`
  - Windows: `$HOME/_vimrc` and `$HOME/.vim`
- Neovim:
  - Linux: `$HOME/.config/nvim/init.vim` and `$HOME/.config/nvim`
  - Windows: `$HOME/AppData/Local/nvim/init.vim` and `$HOME/AppData/Local/nvim`

Since one configuration can be shared between all four setups (with minor conditionals), I want to have one "hoarded" version of the configuration but correctly apply it based on environment.

The application is easy enough: copy from the hoard onto the filesystem. But how do we store these in the first place? Naively using the top-level name doesn't work if there are any conflicts. So some sort of unique id seems necessary.

How would we derive an id?
- A hash of the file path doesn't work, since there are multiple paths based on environment
- A hash of the first or of all paths together doesn't work, because order can change and a new path can be introduced at any time, both of which could change the hash.
- Can't use the file contents, because those will change.

Perhaps how we set up configuration can make a difference. So what would configuration look like?

```toml

[environments]
[environments.winvim]
# ...
[environments.linvim]
# ...
[environments.winneo]
# ...
[environments.linneo]
# ...

[hoard]
[hoard.vim]
    [[hoard.vim.files]]
        id = "rcfile"
        envs = {
            winvim = "$HOME/_vimrc",
            linneo = "$HOME/.config/nvim/init.vim",
            # ...
        }
```

... Maybe something else? Maybe using JSON instead?
